name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          comment_tag_name: "START_SECTION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}